server:
  port: 8001

logging:
  config:
    classpath:logback-springboot-${spring.profiles.active}.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

spring:
  application:
    name: account
  profiles:
      active: dev
  datasource:
    #name: pretty-api
    url: jdbc:mysql://47.99.207.124:3306/app?characterEncoding=utf8&autoReconnect=true&tinyInt1isBit=false
    username: base
    password: Base+627
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 127.0.0.1
    #host: 47.96.103.86
    #host: 172.16.163.104
    port: 6379
    #password: moon-mon
    #password: Ylmm2018
    database: 0
    pool:
        max-idle: 300
        min-idle: 100
        max-active: 600
        max-wait: 5000
    timeout: 0
  http:
    encoding:
      charset: utf-8
      enabled: true
mybatis:
    type-aliases-package: com.app.cloud.**.entity
    #mapper-locations: classpath:mapper/**/*.xml
    #config-locations: classpath:conf/mybatis-config.xml

mapper:
    mappers: com.app.cloud.web.BaseMapper
    not-empty: false
    identity: MYSQL