
server:
  port: 7002

eureka:
  instance:
    hostname: backup
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://master:7001/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://127.0.0.1:7001/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 10000