
server:
  port: 8888

spring:
  application:
    name: config-center
  profiles:
    active: dev
  cloud:
    config:
      profile: ${spring.profiles.active}
      server:
        git:
          default-label: master
          search-paths: /**
          uri: https://github.com/pure-work/project.app.cloud.config.git
          #basedir: config-center/target/config

logging:
  config:
    classpath:logback-springboot-${spring.profiles.active}.xml