spring:
  application:
    name: gate-way
  profiles:
    active: dev

server:
  port: 80

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7001/eureka/

logging:
  config:
    classpath:logback-springboot-${spring.profiles.active}.xml
#zuul:
  #routes:
    #account:
      #path: /api/account/**
      #serviceId: account
      #serviceId: account-service